apiVersion: v1
kind: Service
metadata:
  name: donor-front-service
  namespace: bloodbank
  labels:
    env: dev
    app: donor-front-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30007
  selector:
    app: donor-front